{
 "title": "CrateDB Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "buoyId",
    "label": "Buoy",
    "query": "SELECT DISTINCT entity_id FROM etwaterquality;"
   }
  ]
 },
 "panels": [
  {
   "title": "Water level",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT dateobserved, level FROM etwaterquality LIMIT 50 "
    }
   ]
  },
  {
   "title": "ph",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ph FROM etwaterquality WHERE entity_id = '$buoyId' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT dateobserved, temperature FROM etwaterquality WHERE entity_id = '$buoyId' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cloro",
   "type": "gauge",
   "description": "Nivel de cloro en el agua",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT chlorine FROM etwaterquality LIMIT 50 "
    }
   ]
  }
 ]
}