{
 "title": "Dashboard_v2",
 "time": { "from": "2024-04-05T18:00:00.000Z", "to": "2024-04-21T13:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "buoyId",
    "label": "Sensor",
    "query": "SELECT DISTINCT entity_id FROM etwaterquality;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Nivel geolocalizado",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    a.entity_id, \r\n    a.dateobserved, \r\n    a.location_centroid, \r\n    latitude(a.location_centroid) AS longitude, \r\n    longitude(a.location_centroid) AS latitude, \r\n    a.\"level\"\r\nFROM \r\n    etwaterquality a\r\nINNER JOIN (\r\n    SELECT \r\n        entity_id, \r\n        MAX(dateobserved) AS MaxDate\r\n    FROM \r\n        etwaterquality\r\n    GROUP BY \r\n        entity_id\r\n) b ON a.entity_id = b.entity_id AND a.dateobserved = b.MaxDate limit 100;"
    }
   ]
  },
  {
   "title": "Turbidez",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT dateobserved, turbidity FROM etwaterquality WHERE entity_id = '$buoyId' LIMIT 50 "
    }
   ]
  },
  {
   "title": "ph",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dateobserved, ph FROM etwaterquality WHERE entity_id = '$buoyId' LIMIT  50 "
    }
   ]
  },
  {
   "title": "Cloro",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dateobserved, chlorine FROM etwaterquality WHERE entity_id = '$buoyId' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT dateobserved, temperature FROM etwaterquality WHERE entity_id = '$buoyId' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Conductividad",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dateobserved, conductivity FROM etwaterquality WHERE entity_id = '$buoyId' LIMIT 50 "
    }
   ]
  }
 ]
}