### Send POST request with json body
POST {{orion}}/v2/entities
Content-Type: application/json

{
  "id": "Barlovento",
  "type": "CalidadAgua",
  "location": {
    "value": {
      "type": "Point",
      "coordinates": [
        28.81,
        -17.801
      ]
    },
    "type": "geo:json"
  },
  "temperature": {
    "type": "Number",
    "value": "22.5"
  },
  "ph": {
    "type": "Number",
    "value": "6.9"
  },
  "turbidity": {
    "type": "Number",
    "value": "0.7"
  },
  "conductivity": {
    "type": "Number",
    "value": "0.2"
  },
  "water_lvl": {
    "type": "Number",
    "value": "4.2"
  },
  "chlorine": {
    "type": "Number",
    "value": "0.3"
  },
  "dateObserved": {
    "type": "DateTime",
    "value": "2024-05-01T00:00-00:00"
  }
}


###
// 28.81
// -17.80