### Send PATCH to fetch all entities
PATCH {{orion}}/v2/entities/Vicario/attrs
Content-Type: application/json

{
  "dateObserved": {
    "type": "DateTime",
    "value": "2014-05-03T14:00:00.000Z"
  },
  "location": {
    "value": {
      "type": "Point",
      "coordinates": [28.81, -17.801]
    },
    "type": "geo:json"
  }
}
