### Send POST request with json body
POST {{orion}}/v2/subscriptions
Content-Type: application/json

{
  "description": "Subscripción QuantumLeap a calidad del agua",
  "subject": {
    "entities": [
      {
        "idPattern": ".*",
        "type": "CalidadAgua"
      }
    ],
    "condition": {
      "attrs": [
        "chlorine",
        "conductivity",
        "water_lvl",
        "ph",
        "turbidity",
        "temperature",
        "dateobserved"
      ]
    }
  },
  "notification": {
    "attrs": [
      "type",
      "chlorine",
      "conductivity",
      "water_lvl",
      "ph",
      "turbidity",
      "temperature",
      "location",
      "dateobserved"
    ],
    "http": {
      "url": "{{quantumleap}}/v2/notify"
    },
    "metadata": [
      "dateCreated",
      "dateModified"
    ]
  }
}
